CREATE TABLE `usuario`
(`id` int(11) AUTO_INCREMENT,
`usuario` VARCHAR(50) NOT NULL,
`senha` VARCHAR(255) NOT NULL,
`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(`id`));